### ISSUE TITLE
Calling status.sh fails 

### ISSUE THREAD

**Issue by stochastic-thread** [helium/BEAMCoin#3]
I am able to run `./scripts/genesis.sh satoshi` and it starts to "mine" despite there being no transactions.

However, when I (from another terminal), attempt to run `./scripts/status.sh satoshi` I get this crash message:

```
blockchain is of height 61 with head 327d694a1b64adeccc328672228946b1c25e6cc8e836646c6cd9164b2eb50000
{"init terminating in do_boot",{badarg,[{ets,match,[#Ref<2582.2946454078.122028034.137125>,{{listener,'$1'},'_'}],[]},{libp2p_config,listen_addrs,1,[{file,"/Users/acolle/Code/BEAMCoin/_build/default/lib/libp2p/src/libp2p_config.erl"},{line,151}]},{beamcoin,status,1,[{file,"/Users/acolle/Code/BEAMCoin/_build/default/lib/beamcoin/src/beamcoin.erl"},{line,107}]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ({badarg,[{ets,match,[,{_}],[]},{libp2p_config,listen_addrs,1,[{_},{_}]},{beamcoin,status,1,[{_},{_}]},{init,start_em,1,[]},{init,do_boot,3,[]}]})

Crash dump is being written to: erl_crash.dump...done
```

I attached the erl_crash.dump file. Can someone point me in the right direction in terms of what is causing the status command to fail?

Any help would be greatly appreciated!

[erl_crash.dump.txt](https://github.com/helium/BEAMCoin/files/3408156/erl_crash.dump.txt)

**Comment by madninja** [comment]
HI @stochastic-thread..This repo was used only for a few days [as part of a talk](https://codesync.global/media/bridging-the-physical-and-blockchain-world-with-erlang/) that @Vagabond gave at a conference a year or so ago. 

I will archive the repo as it's no longer maintained. Sorry for the confusion
